# --- Created by Slick DDL

# --- !Ups

create table "TODO" ("ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"CONTENT" TEXT NOT NULL);

# --- !Downs

drop table "TODO";

